charts/console/Chart.yaml
charts/console/templates/deployment.yaml

@CristhianF7 I believe this should be what is desired!

Interval update

---

.github/workflows/kubefirst-releaser-dev.yaml

initial ci skeleton for triggering kubefirst dev environment

---

charts/kubefirst/Chart.yaml

updating the macro chart to be in alignment with offline testing

bump chart to sync with testing

---

charts/kubefirst/values.yaml

adjusting values.yaml version

---

.argo/promote.yaml
.github/workflows/kubefirst-staging.yaml

chore: promote macro chart ci

---

.argo/promote.yaml

fix: source filepath for chart version

---

.argo/kubefirst-release.yaml
.argo/kubefirst-staging.yaml

updating get-macro-chart-version-from-gitops-repo as source for version

---

.argo/kubefirst-release.yaml

renegotiate step names

---

.argo/kubefirst-release.yaml
charts/kubefirst/Chart.yaml
charts/kubefirst/values.yaml

adopts new cwfts to negotiate the values.yaml of the macro chart to accommodate the version number in release automation

fix: patch release ci updates for values.yaml

---

charts/kubefirst/Chart.yaml

prep kubefirst macro chart for a 2.4.16 patch release

prep kubefirst macro chart for a 2.4.16 patch release

---

charts/kubefirst/Chart.yaml

reset macro chart for a 2.4.16 patch release

reset macro chart for a 2.4.16 patch release

---

charts/kubefirst/Chart.yaml

chart rc bump

---

.argo/metaphor-publish-rc-chart.yaml
.argo/metaphor-release.yaml
.argo/metaphor-staging.yaml
.github/workflows/metaphor-publish-rc-chart.yaml
.github/workflows/metaphor-release.yaml
.github/workflows/metaphor-staging.yaml

feat: add metaphor workflow

---

charts/metaphor-macro/Chart.yaml
charts/metaphor-macro/values.yaml

bumping to 0.10.0-rc1 for metaphor

---

charts/kubefirst/Chart.yaml

patch bump kubefirst rc chart

---

.argo/kubefirst-pro-publish-rc-chart.yaml
.argo/kubefirst-release.yaml
.github/workflows/kubefirst-pro-publish-rc-chart.yaml

This PR adds Kubefirst Pro CI accordingly 
Fixes https://linear.app/konstruct/issue/KRA-10/new-macro

feat:kubefirst pro ci

---

charts/kubefirst-pro/values.yaml
charts/kubefirst/Chart.yaml

Fixing chart version for kubefirst oss

fix: chart versions

---

charts/colony/Chart.yaml

Update Chart.yaml: bump to +1 number

---

charts/kubefirst-pro/Chart.yaml
charts/kubefirst-pro/values.yaml
charts/kubefirst/Chart.yaml
charts/kubefirst/values.yaml

chore: bump version 2.7.0

---

.argo/kubefirst-release.yaml

- Fixes `Failed to submit workflow: templates.main.steps[5].name 'set-macro-chart-version' is not unique"`. Names should be unique

fix: kubefirst release

---

.argo/kubefirst-release.yaml

fix: repo source for publish

---

charts/kubefirst-pro/Chart.yaml
charts/kubefirst-pro/values.yaml
charts/kubefirst/Chart.yaml
charts/kubefirst/values.yaml

- Bumps kubefirst pro and kubefirst oss version

chore: bump versions

---

charts/kubefirst-pro/Chart.yaml
charts/kubefirst-pro/values.yaml
charts/kubefirst/Chart.yaml
charts/kubefirst/values.yaml

chore: bump version 2.8.0
